[package]
name = "tls-example"
version = "0.1.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
workspace = "../"

[[bin]]
name = "server"
path = "src/main.rs"

[dependencies]
env_logger = "0.5"
openssl = { version="0.10" }
actix = "0.7"
#actix-web = "^0.7"
actix-web = { git = "https://github.com/actix/actix-web.git" }
