[package]
name = "middleware-ext-mut"
version = "0.1.0"
authors = ["Eric McCarthy <ericmccarthy7@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "4.0.0-beta.21"
log = "0.4"
env_logger = "0.9"
