[package]
name = "async-graphql-demo"
version = "1.0.0"
edition = "2021"

[dependencies]
actix.workspace = true
actix-web.workspace = true
actix-web-lab.workspace = true
actix-cors.workspace = true

async-graphql = "5"
async-graphql-actix-web = "5"

env_logger.workspace = true
log.workspace = true
slab = "0.4"
