[package]
name = "actix-web-cors"
version = "1.0.0"
authors = ["krircc <krircc@aliyun.com>"]
edition = "2018"

[dependencies]
actix-rt = "1.0.0"
actix-web = "2.0.0"
actix-cors = "0.2.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
dotenv = "0.10"
env_logger = "0.6"
futures = "0.3"
