[package]
name = "cookie-auth"
version = "0.1.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
edition = "2018"
workspace = ".."

[dependencies]
actix-web = { git="https://github.com/actix/actix-web.git", branch = "1.0" }
env_logger = "0.6"
