[package]
name = "cookie-auth"
version = "0.1.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
workspace = "../"

[dependencies]
actix-web = { git="https://github.com/actix/actix-web.git" }
env_logger = "0.5"
