language: rust
dist: xenial

addons:
  apt:
    sources:
      - ppa:chris-lea/redis-server
    packages:
      - redis-server

services:
  - redis-server

cache:
  apt: true
  directories:
    - $HOME/.cargo
    - $HOME/.rustup

before_cache:
  - rm -rf $HOME/.cargo/registry

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
  allow_failures:
    - rust: nightly

env:
  global:
    # - RUSTFLAGS="-C link-dead-code"
    - OPENSSL_VERSION=openssl-1.1.1

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -y install libssl-dev libelf-dev libdw-dev binutils-dev libiberty-dev

# Add clippy
before_script:
  - |
    if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
      rustup component add clippy --toolchain=nightly
    fi
  - export PATH=$PATH:~/.cargo/bin

script:
  - cargo check --all
  - cargo test --all --no-fail-fast
  - |
    if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
      cargo clippy
    fi
