[workspace]
members = [
   "auth/casbin",
   "auth/cookie-auth",
   "auth/cookie-session",
   "auth/redis-session",
   "auth/simple-auth-server",
   "basics/basics",
   "basics/error_handling",
   "basics/hello-world",
   "basics/json-validation",
   "basics/nested-routing",
   "basics/state",
   "basics/static_index",
   "basics/todo",
   "cors/backend",
   "data_factory",
   # example uses incompatible libsqlite-sys to other examples
   # "databases/diesel",
   "databases/mongodb",
   "databases/postgres",
   "databases/redis",
   "databases/sqlite",
   "docker",
   "forms/form",
   "forms/multipart-s3",
   "forms/multipart",
   "graphql/async-graphql",
   "graphql/juniper-advanced",
   "graphql/juniper",
   "http-proxy",
   "https-tls/awc_https",
   "https-tls/openssl-auto-le",
   "https-tls/openssl",
   "https-tls/rustls-client-cert",
   "https-tls/rustls",
   "json/json_decode_error",
   "json/json_error",
   "json/json",
   "json/jsonrpc",
   "middleware/middleware-ext-mut",
   "middleware/middleware-http-to-https",
   "middleware/middleware",
   "protobuf",
   "run-in-thread",
   "server-sent-events",
   "shutdown-server",
   "templating/askama",
   "templating/handlebars",
   "templating/sailfish",
   "templating/tera",
   "templating/tinytemplate",
   "templating/yarte",
   "unix-socket",
   "websockets/autobahn",
   "websockets/chat-broker",
   "websockets/chat-tcp",
   "websockets/chat",
   "websockets/echo",
]
