[package]
name = "json_error"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-web = { workspace = true }

env_logger.workspace = true
log.workspace = true
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
