[package]
name = "template_yarte"
version = "0.0.1"
authors = ["Juan Aguilar Santillana <mhpoin@gmail.com>"]
publish = false
edition = "2018"

[dependencies]
actix-web = "4.0.0-rc.1"
env_logger = "0.9.0"
yarte = { version = "0.15", features = ["bytes-buf", "html-min"] }
derive_more = "0.99"

[build-dependencies.yarte_helpers]
version = "0.15.6"
default-features = false
features = ["config"]
