[package]
name = "templating-askama"
version = "1.0.0"
edition = "2021"

[dependencies]
env_logger.workspace = true
actix-web.workspace = true
askama = "0.11.0"

[build-dependencies]
askama = "0.11.0"
