[package]
name = "middleware-http-to-https"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-web = {version = "4.0.0-beta.21", features = ["rustls"]}
rustls = "0.20.2"
rustls-pemfile = "0.2.1" # these are now in an external library
futures = "0.3"
