[package]
name = "websocket-chat-broker"
version = "1.0.0"
edition = "2021"

[[bin]]
name = "server"
path = "src/main.rs"

[dependencies]
actix = "0.12"
actix-broker = "0.4"
actix-files = "0.6.0-beta.16"
actix-web = "4.0.0-rc.3"
actix-web-actors = "4.0.0-beta.12"

env_logger = "0.9"
log = "0.4"
rand = "0.8"
