[package]
name = "form-example"
version = "1.0.0"
authors = ["Gorm Casper <gcasper@gmail.com>"]
edition = "2018"
workspace = ".."

[dependencies]
actix-web = "2.0.0-alpha.6"
actix-rt = "1.0.0"
serde = "1.0"
serde_derive = "1.0"
