[package]
name = "middleware-example"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-http.workspace = true
actix-web.workspace = true
actix-web-lab.workspace = true

env_logger.workspace = true
futures-util.workspace = true
log.workspace = true
pin-project = "1"
