[package]
name = "basics"
version = "1.0.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
workspace = "../"
edition = "2018"

[dependencies]
actix-rt = "0.1"
actix-web = { git="https://github.com/actix/actix-web.git", branch = "1.0" }
actix-session = { git="https://github.com/actix/actix-web.git", branch = "1.0" }
actix-staticfiles = { git="https://github.com/actix/actix-web.git", branch = "1.0" }

futures = "0.1.25"
env_logger = "0.5"
bytes = "0.4"
