[package]
name = "websocket-chat-actorless-example"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-files = { workspace = true }
actix-web = { workspace = true }
actix-ws = { workspace = true }
awc = "3"

derive_more = "0.99.5"
env_logger.workspace = true
futures-util = { version = "0.3.17", default-features = false, features = ["std"] }
log.workspace = true
rand = "0.8"
tokio = { version = "1.13.1", features = ["rt", "macros", "sync", "time"] }
