[package]
name = "actix_redis"
version = "1.0.0"
edition = "2021"

[dependencies]
actix = "0.12"
actix-redis = "0.10"
actix-web = "4"

env_logger = "0.9"
futures-util = { version = "0.3.7", default-features = false, features = ["std"] }
log = "0.4"
redis-async = { version = "0.8", default_features = false, features = ["tokio10"] }
serde = { version = "1", features = ["derive"] }
