[package]
name = "server-sent-events"
version = "1.0.0"
authors = ["Arve Seljebu"]
workspace = ".."
edition = "2018"

[dependencies]
actix-rt = "1.0.0"
actix-web = "2.0.0-rc"
env_logger = "0.6"
futures = "0.3.1"
tokio = "0.2"