[package]
name = "static_index"
version = "2.0.0"
authors = ["Jose Marinez <digeratus@gmail.com>"]
workspace = ".."
edition = "2018"

[dependencies]
futures = "0.3.1"
env_logger = "0.6"

actix-web = "2.0.0-alpha.6"
actix-files = "0.2.0-alpha.3"
actix-rt = "1.0.0"
