[package]
name = "shutdown-server"
version = "1.0.0"
edition = "2021"
description = "Send a request to the server to shut it down"

[dependencies]
actix-web = "4"

env_logger = "0.9"
tokio = { version = "1.16", features = ["signal"] }
