[package]
name = "websocket-example"
version = "0.1.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
workspace = ".."
edition = "2018"

[[bin]]
name = "websocket-chat-server"
path = "src/main.rs"

[dependencies]
actix = "0.8.0-alpha.2"
actix-web = "1.0.0-alpha.3"
actix-web-actors = "1.0.0-alpha.3"
actix-files = "0.1.0-alpha.2"

rand = "0.6"
bytes = "0.4"
byteorder = "1.1"
futures = "0.1.25"
tokio-io = "0.1"
env_logger = "0.6"
serde = "1.0"
serde_json = "1.0"
