[package]
name = "json-example"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-web.workspace = true

env_logger.workspace = true
futures-util.workspace = true
json = "0.12"
log.workspace = true
serde = { version = "1.0", features = ["derive"] }
serde_json.workspace = true
