[package]
name = "websocket-tcp-example"
version = "2.0.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
edition = "2018"

[[bin]]
name = "websocket-tcp-server"
path = "src/main.rs"

[[bin]]
name = "websocket-tcp-client"
path = "src/client.rs"

[dependencies]
actix = "0.9.0-alpha.2"
actix-web = "2.0.0-alpha.6"
actix-web-actors = "2.0.0-alpha.1"
actix-files = "0.2.0-alpha.3"
actix-rt = "1.0.0"
actix-codec = "0.2.0"

rand = "0.7"
bytes = "0.5.3"
byteorder = "1.2"
futures = "0.3"
env_logger = "0.6"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
tokio = "0.2.4"
tokio-util = "0.2.0"