[package]
name = "json-validation"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-web = "4"
awc = { version = "3.0.0-beta.21", features = ["openssl"] }

env_logger = "0.9"
futures-util = { version = "0.3.7", default-features = false, features = ["std"] }
log = "0.4"
serde = { version = "1.0.43", features = ["derive"] }
serde_json = "1.0.16"
validator = "0.14"
validator_derive = "0.14"
