[package]
name = "redis-session"
version = "0.1.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
workspace = ".."
edition = "2018"

[dependencies]
actix = "0.8.2"
actix-web = "1.0.3"
actix-session = "0.1.0"
actix-redis = { version = "0.6", features = ["web"] }
env_logger = "0.6"
