[package]
name = "juniper-advanced"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-web = "4.0.0-rc.3"
actix-web-lab = "0.10"
actix-cors = "0.6.0-beta.10"

juniper = "0.15"

mysql = "17"
r2d2 = "0.8"
r2d2_mysql = "17"

dotenv = "0.15"
env_logger = "0.9"
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "0.8", features = ["serde", "v4"] }
