[package]
name = "multipart-s3"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-multipart = "0.4"

dotenv = "0.15.0"
env_logger = "0.9"
futures-util = { version = "0.3.17", default-features = false, features = ["std"] }
log = "0.4"
rusoto_core = "0.48"
rusoto_s3 = "0.48"
sanitize-filename = "0.4"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0"
