[package]
name = "middleware-example"
version = "2.0.0"
authors = ["Gorm Casper <gcasper@gmail.com>", "Sven-Hendrik Haase <svenstaro@gmail.com>"]
edition = "2021"

[dependencies]
actix-web = "4.0.0-rc.1"
env_logger = "0.9"
futures = "0.3.7"
pin-project = "1"
