[package]
name = "websocket"
version = "2.0.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
edition = "2018"

[[bin]]
name = "websocket-server"
path = "src/main.rs"

[[bin]]
name = "websocket-client"
path = "src/client.rs"

[dependencies]
actix = "0.9.0"
actix-codec = "0.2.0"
actix-web = "2.0.0-rc"
actix-web-actors = "2.0.0"
actix-files = "0.2.0"
actix-rt = "1.0.0"
awc = "1.0.1"
env_logger = "0.6"
futures = "0.3.1"
bytes = "0.5.3"
