[package]
name = "actix_redis"
version = "1.0.0"
authors = ["dowwie <dkcdkg@gmail.com>"]
edition = "2018"

[dependencies]
actix = "0.9.0-alpha.2"
actix-rt = "1.0.0"
actix-web = "2.0.0-alpha.6"
actix-redis = "0.8.0-alpha.1"
futures = "0.3.1"
redis-async = "0.6.1"
serde = "1.0.71"
serde_derive = "1.0.71"
env_logger = "0.6"
