[package]
name = "template-askama"
version = "2.0.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "2.0.0-rc"
actix-rt = "1.0.0"
env_logger = "0.6"
askama = "0.8"

[build-dependencies]
askama = "0.8"
