[package]
name = "websocket-echo-actorless-example"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-files = { workspace = true }
actix-web = { workspace = true }
actix-ws = { workspace = true }
awc = "3"

env_logger.workspace = true
futures-util = { version = "0.3.17", default-features = false, features = ["std"] }
log.workspace = true
tokio = { version = "1.13.1", features = ["rt", "macros", "sync", "time"] }
