[package]
name = "websocket-echo-actorless-example"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-files = "0.6"
actix-web = "4"
actix-ws = "0.2.5"
awc = "3"

env_logger = "0.9"
futures-util = { version = "0.3.7", default-features = false, features = ["std", "sink"] }
futures-lite = "1.3"
log = "0.4"
tokio = { version = "1.13.1", features = ["full"] }
